FindBugs code cleanups (1/13) - EmptyQVariantException.
EmptyQVariantException: make this class actually extend Exception, not Throwable. Fixes a FindBugs complaint (because the class contains "Exception" in the name).